{% set name = "cif2cell" %}
{% set version = "2.0.0a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/torbjornbjorkman/cif2cell/archive/refs/tags/{{ version }}.tar.gz
  sha256: 906bfde60ba6bab7c2e35cac0a3b010061a4339c36bcb5b723e63691ec3148af

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pycifrw
  run:
    - python >=3.6
    - pycifrw

test:
  commands:
    - cif2cell -h

about:
  home: https://sourceforge.net/projects/cif2cell/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'CIF2Cell is a tool to generate the geometrical setup for various electronic structure codes from a CIF (Crystallographic Information Framework) file.'

extra:
  recipe-maintainers:
    - ltalirz
    - npavlovikj
