appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZzFVfDYRGt6pq6jNxcdo/3VbMgeOk7pkRyy/MmZ1H9rTdIf5sVN4lvf+niLxiKWPDvBcRhnEs5UswNRB8CJBcmTHVsxaiQHxxP9M20syl7ruuGcvo2s/ax85ioXiuk9P/VslBPVi3kVm7oQOOCAK+6pyxz67s4TzAs9kB/FTpD5mKmM2mG6RZW/x6+WYguX9yLRSHfCdIwO2zL4STWLrIewrd4Dqenzj+W9c6YYyR0qAkzWG/ATSHLz9tfT4DzrFcucQ67g+rK3XReGd64qJlP/2yBS3U4e8vZey69MuUBoKzhbQkhaBpM9qa64ZOSDdDItBAj7Qfvr18qdMS2rDkh70leWuLlapIMk8dnnp5HjbjaC1+GII9zxP2/8fG8HuZWEN40Iz9cYjosoXChscXeiSgDAtQiJdnCQdz/OLYJ4ucMoyFYcYWtNJlTGdAe+u1Cqo5ew5bJ1S+HoX6ZiIKrMizY2iN4piQiaAgA3upRyVxNv1oX02MNOJhaDtb/tahnGefgyPjcY0fPC9RNXbK6qrs+ZNxX8I5at4iYRJz6IqDr+tjLUS7Bigpbg/fu5aHgak7D6awCxFDCpoKdAtP4BfL8NRQPWC1vA+me/0TLBbr8iZBxN7oD2QY42IVF8uHFOgMhvXrIYpg2VugH0GEuSghTEdE1ZNfvG2GSQVSgg=}
